services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=splearn
      - MYSQL_USER=spring
      - MYSQL_PASSWORD=secret
    ports:
      - '3306:3306'
