spring:
  datasource:
    url: jdbc:h2:file:./spring/spring-db2/spring-db2-itemservice/db
    username: sa
    password: 1234
  sql:
    init:
      mode: always

mybatis:
  type-aliases-package: com.hoonjin.study.spring.db2.itemservice.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.jdbc: debug
    com.hoonjin.study.spring.db2.itemservice.repository: trace
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
